# 🏏 NumPy Assignment — Cricket Performance Analytics Engine
### Module 01 | neural-nomad-ai-lab
**Scenario:** You have been hired as a junior data scientist at a cricket analytics company.
Your job is to build a performance analysis engine using only NumPy — no Pandas, no loops where vectorization is possible.
This assignment tests your ability to manipulate arrays, apply mathematical operations, use broadcasting, and extract meaningful insights from raw numerical data.

In [1]:
import numpy as np
np.random.seed(42)

In [2]:
scores = np.array([
    [45,  82,   0, 134,  56,  23,  78,  12,  90,  45],
    [90,  45,  67,  12,  88,  34,   0,  56, 112,  34],
    [12,   0,  55,  78,  23,  99,  43,   0,  67,  88],
    [67,  34,  89,  45,  11,  56,  23,  78,  34,  90],
    [23,  56,  78, 100,  34,  67, 145,  89,  56,  23],
    [0,   45,  34,  67,  89,  12,  56,  34,  78,  56],
    [89, 112,  45,   0,  67,  78,  34,  90,  23,  45],
    [34,  23,  90,  56,  45,  89,  67,  12, 134,  78],
])

In [3]:
batsmen = ['Rohit', 'Virat', 'Gill', 'Iyer', 'Hardik', 'Jadeja', 'Rahul', 'Pant']
matches = [f'Match {i}' for i in range(1, 11)]

In [4]:
# Strike rates for each batsman (runs per 100 balls faced)
strike_rates = np.array([136.5, 138.2, 142.1, 128.4, 155.3, 118.7, 134.9, 148.6])

# Match difficulty weights (some pitches harder than others)
pitch_difficulty = np.array([1.0, 1.2, 1.5, 0.8, 1.1, 1.3, 0.9, 1.4, 1.0, 1.2])

print("Dataset loaded.")
print(f"Shape: {scores.shape} → {scores.shape[0]} batsmen × {scores.shape[1]} matches")

Dataset loaded.
Shape: (8, 10) → 8 batsmen × 10 matches


## Section 1 — Array Fundamentals
Inspecting data before any analysis.


In [11]:

print("Shape:     ", scores.shape)
print("Dimensions:", scores.ndim)
print("Total elements:", scores.size)
print("Dtype:     ", scores.dtype)
print("Memory (bytes):", scores.nbytes)


print("\nTotal runs (all):", scores.sum())
print("Overall average: ", scores.mean().round(2))


is_duck    = scores == 0
print(is_duck)
print("\nTotal ducks:", is_duck.sum())

ducks_per_batsman = is_duck.sum(axis=1)
most_ducks_idx    = np.argmax(ducks_per_batsman)
print(f"Most ducks: {batsmen[most_ducks_idx]} ({ducks_per_batsman[most_ducks_idx]} ducks)")

Shape:      (8, 10)
Dimensions: 2
Total elements: 80
Dtype:      int64
Memory (bytes): 640

Total runs (all): 4448
Overall average:  55.6
[[False False  True False False False False False False False]
 [False False False False False False  True False False False]
 [False  True False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False  True False False False False False False]
 [False False False False False False False False False False]]

Total ducks: 6
[1 1 2 0 0 1 1 0]
Most ducks: Gill (2 ducks)


## Section 2 — Indexing, Slicing & Fancy Indexing
Extracting specific subsets of data.

In [12]:
# TASK 2.1 — Using iloc:
# a) Select rows 10 to 20
# b) Select the last 5 rows and first 4 columns
# c) Select every 3rd row
virat_scores    = scores[1]
virat_last6     = scores[1, 4:]          # matches 5-10 → index 4 to end
print("Virat all:   ", virat_scores)
print("Virat last 6:", virat_last6)

# TASK 2.2 — Using loc:
# a) Select all pitches where a deal WAS made
#    (find the right column name first by inspecting the df)
# b) From those deals, show only: startup name, ask amount,
#    deal amount, and the industry column
match3_and_7 = scores[:, [2, 6]]        # columns 2 and 6
print("\nMatch 3 & 7 scores:\n", match3_and_7)

# TASK 2.3 — Set the startup name as the index
# Then use .loc to retrieve the row for a specific startup of your choice
# Reset the index back to default after
selected = scores[[0, 4, 7], :]         # Rohit=0, Hardik=4, Pant=7
print("\nRohit, Hardik, Pant:\n", selected)


# TASK 2.4 — Multi-condition selection (no .query() here — use & and |):
# Find pitches where:
# - A deal WAS made, AND
# - The deal amount is LESS than what was originally asked
# How many startups accepted a lower deal? Print the count and the rows.
centuries_mask   = scores > 100
print("\nCenturies scored:", centuries_mask.sum())
print("Scores:",            scores[centuries_mask])

# Which batsmen scored centuries? (at least one True in their row)
batsmen_with_100 = centuries_mask.any(axis=1)
print("Batsmen with centuries:", [b for b, has in zip(batsmen, batsmen_with_100) if has])

# TASK 2.5
max_score   = scores.max()
idx_flat    = scores.argmax()            # flat index
row, col    = np.unravel_index(idx_flat, scores.shape)
print(f"\nHighest score: {max_score} by {batsmen[row]} in Match {col+1}")



Virat all:    [ 90  45  67  12  88  34   0  56 112  34]
Virat last 6: [ 88  34   0  56 112  34]

Match 3 & 7 scores:
 [[  0  78]
 [ 67   0]
 [ 55  43]
 [ 89  23]
 [ 78 145]
 [ 34  56]
 [ 45  34]
 [ 90  67]]

Rohit, Hardik, Pant:
 [[ 45  82   0 134  56  23  78  12  90  45]
 [ 23  56  78 100  34  67 145  89  56  23]
 [ 34  23  90  56  45  89  67  12 134  78]]

Centuries scored: 5
Scores: [134 112 145 112 134]
Batsmen with centuries: ['Rohit', 'Virat', 'Hardik', 'Rahul', 'Pant']

Highest score: 145 by Hardik in Match 7


## Section 3 — Reshaping, Stacking & Manipulation
Real data rarely arrives in the right shape. Lets make it so that its as needed.


In [15]:
# TASK 3.1 — Reshape scores into (10, 8): matches as rows, batsmen as cols
# Print the new shape and the first 3 rows
reshaped = scores.reshape(10, 8)
print("New shape:", reshaped.shape)
print("First 3 rows:\n", reshaped[:3])

# TASK 3.2 — Flatten the entire scores matrix into a 1D array
# Sort it in descending order and print the top 10 scores (tournament leaderboard)
flat_sorted = np.sort(scores.flatten())[::-1]
print("\nTop 10 scores:", flat_sorted[:10])

# TASK 3.3 — Create a match number array [1, 2, ..., 10]
# Stack it as a new row on TOP of the scores matrix using vstack
# New shape should be (9, 10). Print it.
match_nums   = np.arange(1, 11).reshape(1, 10)
stacked      = np.vstack([match_nums, scores])
print("\nStacked shape:", stacked.shape)
print(stacked)

# TASK 3.4 — Split the scores matrix into two halves:
# first 5 matches and last 5 matches (use np.hsplit)
# Print both halves and their shapes
first_half, second_half = np.hsplit(scores, 2)
print("\nFirst 5 matches shape:",  first_half.shape)
print("Last 5 matches shape:",    second_half.shape)
print("First half:\n",  first_half)
print("Second half:\n", second_half)

# TASK 3.5 — Transpose the scores matrix.
# What does the transposed matrix represent?
# Write your answer in a comment.
transposed = scores.T
print("\nTransposed shape:", transposed.shape)


New shape: (10, 8)
First 3 rows:
 [[ 45  82   0 134  56  23  78  12]
 [ 90  45  90  45  67  12  88  34]
 [  0  56 112  34  12   0  55  78]]

Top 10 scores: [145 134 134 112 112 100  99  90  90  90]

Stacked shape: (9, 10)
[[  1   2   3   4   5   6   7   8   9  10]
 [ 45  82   0 134  56  23  78  12  90  45]
 [ 90  45  67  12  88  34   0  56 112  34]
 [ 12   0  55  78  23  99  43   0  67  88]
 [ 67  34  89  45  11  56  23  78  34  90]
 [ 23  56  78 100  34  67 145  89  56  23]
 [  0  45  34  67  89  12  56  34  78  56]
 [ 89 112  45   0  67  78  34  90  23  45]
 [ 34  23  90  56  45  89  67  12 134  78]]

First 5 matches shape: (8, 5)
Last 5 matches shape: (8, 5)
First half:
 [[ 45  82   0 134  56]
 [ 90  45  67  12  88]
 [ 12   0  55  78  23]
 [ 67  34  89  45  11]
 [ 23  56  78 100  34]
 [  0  45  34  67  89]
 [ 89 112  45   0  67]
 [ 34  23  90  56  45]]
Second half:
 [[ 23  78  12  90  45]
 [ 34   0  56 112  34]
 [ 99  43   0  67  88]
 [ 56  23  78  34  90]
 [ 67 145  89  56  23]
 [ 

## Section 4 — Vectorized Operations & Mathematical Functions
No loops.


In [18]:
# TASK 4.1 — Compute for each batsman (no loops):
# a) Total runs
# b) Average runs per match
# c) Highest score
# d) Lowest NON-ZERO score (Hint: use masking to exclude ducks first)
# Print a clean summary

total_runs = scores.sum(axis=1)
avg_runs   = scores.mean(axis=1)
high_score = scores.max(axis=1)
masked = np.where(scores == 0, np.inf, scores)   # replace 0 with inf so min ignores ducks
low_nonzero = masked.min(axis=1)

for i, b in enumerate(batsmen):
    print(f"{b:8} | Total: {total_runs[i]:4} | Avg: {avg_runs[i]:.1f} "
          f"| Best: {high_score[i]:4} | Low (non-zero): {low_nonzero[i]:.0f}")

# TASK 4.2 — Apply pitch difficulty weighting:
# Multiply every batsman's scores by the pitch_difficulty array
# using broadcasting (the difficulty applies per match, across all batsmen)
# Store as 'adjusted_scores'
# Who has the highest ADJUSTED total?
adjusted_scores = scores * pitch_difficulty
adj_totals      = adjusted_scores.sum(axis=1)
best_adj_idx    = np.argmax(adj_totals)
print(f"\nHighest adjusted total: {batsmen[best_adj_idx]} ({adj_totals[best_adj_idx]:.1f})")

# TASK 4.3 — Compute each batsman's "consistency score":
# consistency = mean / std  (higher = more consistent)
# Hint: watch for division by zero if std is 0
# Who is the MOST consistent batsman? Print name + score.
std_per_batsman  = scores.std(axis=1)
mean_per_batsman = scores.mean(axis=1)
consistency      = np.where(std_per_batsman == 0, 0, mean_per_batsman / std_per_batsman)
most_consistent  = np.argmax(consistency)
print(f"\nMost consistent: {batsmen[most_consistent]} (score: {consistency[most_consistent]:.2f})")

# TASK 4.4 — Apply np.log1p (log(1+x)) to all scores
# Why would you use log1p instead of log here? Answer in a comment.
# Print the min, max, and mean of the log-transformed scores.

log_scores = np.log1p(scores)
# log1p is used instead of log because log(0) = -inf (undefined).
# log1p(x) = log(1+x), so log1p(0) = 0 — handles duck scores safely.
print(f"\nLog-transformed — min: {log_scores.min():.3f}, "
      f"max: {log_scores.max():.3f}, mean: {log_scores.mean():.3f}")

# TASK 4.5 — Compute the cumulative runs for Rohit across 10 matches
# (running total after each match) — print it
rohit_cumulative = np.cumsum(scores[0])
print("\nRohit cumulative runs:", rohit_cumulative)

Rohit    | Total:  565 | Avg: 56.5 | Best:  134 | Low (non-zero): 12
Virat    | Total:  538 | Avg: 53.8 | Best:  112 | Low (non-zero): 12
Gill     | Total:  465 | Avg: 46.5 | Best:   99 | Low (non-zero): 12
Iyer     | Total:  527 | Avg: 52.7 | Best:   90 | Low (non-zero): 11
Hardik   | Total:  671 | Avg: 67.1 | Best:  145 | Low (non-zero): 23
Jadeja   | Total:  471 | Avg: 47.1 | Best:   89 | Low (non-zero): 12
Rahul    | Total:  583 | Avg: 58.3 | Best:  112 | Low (non-zero): 23
Pant     | Total:  628 | Avg: 62.8 | Best:  134 | Low (non-zero): 12

Highest adjusted total: Hardik (750.4)

Most consistent: Iyer (score: 2.00)

Log-transformed — min: 0.000, max: 4.984, mean: 3.655

Rohit cumulative runs: [ 45 127 127 261 317 340 418 430 520 565]


## Section 5 — Broadcasting Mastery
Broadcasting is NumPy's superpower.

In [19]:
# TASK 5.1 — Each batsman has a different strike rate bonus multiplier.
# Apply the strike_rates to adjust each batsman's total runs:
# adjusted_total = total_runs * (strike_rate / 100)
# Print the ranking of batsmen by adjusted total (highest to lowest)
# using np.argsort. Print names in order.
adjusted_totals = total_runs * (strike_rates / 100)
ranked_idx      = np.argsort(adjusted_totals)[::-1]   # descending
print("Ranking by strike-rate-adjusted total:")
for rank, idx in enumerate(ranked_idx, 1):
    print(f"  {rank}. {batsmen[idx]:8} — {adjusted_totals[idx]:.1f}")

# TASK 5.2 — Normalise the scores matrix per batsman (row-wise):
# For each batsman, scale their scores between 0 and 1
# relative to their own min and max (not the global min/max)
# Shape must remain (8, 10)
row_min = scores.min(axis=1, keepdims=True)   # shape (8,1) — broadcasts across cols
row_max = scores.max(axis=1, keepdims=True)
row_range = row_max - row_min
normalised_per_batsman = np.where(row_range == 0, 0, (scores - row_min) / row_range)
print("\nRow-normalised shape:", normalised_per_batsman.shape)
print(normalised_per_batsman.round(2))

# TASK 5.3 — Compute the deviation of each score from its match average:
# (how much above/below the match average did each batsman score?)
# Positive = above average, Negative = below average
# Who was most consistently above average?

match_avg   = scores.mean(axis=0, keepdims=True)   # shape (1,10) — broadcasts across rows
deviation   = scores - match_avg
above_avg_count = (deviation > 0).sum(axis=1)       # per batsman
most_above_avg  = np.argmax(above_avg_count)
print(f"\nMost consistently above average: {batsmen[most_above_avg]} "
      f"({above_avg_count[most_above_avg]}/10 matches)")


Ranking by strike-rate-adjusted total:
  1. Hardik   — 1042.1
  2. Pant     — 933.2
  3. Rahul    — 786.5
  4. Rohit    — 771.2
  5. Virat    — 743.5
  6. Iyer     — 676.7
  7. Gill     — 660.8
  8. Jadeja   — 559.1

Row-normalised shape: (8, 10)
[[0.34 0.61 0.   1.   0.42 0.17 0.58 0.09 0.67 0.34]
 [0.8  0.4  0.6  0.11 0.79 0.3  0.   0.5  1.   0.3 ]
 [0.12 0.   0.56 0.79 0.23 1.   0.43 0.   0.68 0.89]
 [0.71 0.29 0.99 0.43 0.   0.57 0.15 0.85 0.29 1.  ]
 [0.   0.27 0.45 0.63 0.09 0.36 1.   0.54 0.27 0.  ]
 [0.   0.51 0.38 0.75 1.   0.13 0.63 0.38 0.88 0.63]
 [0.79 1.   0.4  0.   0.6  0.7  0.3  0.8  0.21 0.4 ]
 [0.18 0.09 0.64 0.36 0.27 0.63 0.45 0.   1.   0.54]]

Most consistently above average: Hardik (6/10 matches)


## Section 6 — Linear Algebra & Advanced Operations

In [20]:
# TASK 6.1 — Compute the correlation matrix between batsmen's performances
# (8x8 matrix). Use np.corrcoef.
# Which two batsmen have the HIGHEST positive correlation?
# (i.e. they tend to score well in the same matches)
# Print their names and the correlation value.
corr_matrix = np.corrcoef(scores)          # (8,8)

# Mask the diagonal (self-correlation = 1.0, not useful)
np.fill_diagonal(corr_matrix, -np.inf)
max_corr_flat  = np.argmax(corr_matrix)
i, j           = np.unravel_index(max_corr_flat, corr_matrix.shape)
print(f"Highest correlation: {batsmen[i]} & {batsmen[j]} → {corr_matrix[i,j]:.3f}")

# TASK 6.2 — Dot product:
# Create a 'weight vector' that gives more importance to recent matches:
weights = np.linspace(0.5, 1.5, 10)  # match 1 weight=0.5, match 10 weight=1.5
# Compute weighted total score for each batsman using np.dot
# Print the weighted rankings
weights         = np.linspace(0.5, 1.5, 10)
weighted_totals = np.dot(scores, weights)    # (8,10) · (10,) = (8,)
weighted_rank   = np.argsort(weighted_totals)[::-1]
print("\nWeighted ranking (recent matches weighted more):")
for rank, idx in enumerate(weighted_rank, 1):
    print(f"  {rank}. {batsmen[idx]:8} — {weighted_totals[idx]:.1f}")

# TASK 6.3 — Covariance:
# Use np.cov to compute the covariance matrix of scores (8x8)
# What does a high covariance between two batsmen tell you?
# Write your interpretation in a comment.
cov_matrix = np.cov(scores)
# High covariance between two batsmen means they tend to score
# high (or low) in the SAME matches — suggesting they perform
# best/worst against similar opposition or conditions.
print("\nCovariance matrix shape:", cov_matrix.shape)





Highest correlation: Gill & Pant → 0.753

Weighted ranking (recent matches weighted more):
  1. Hardik   — 683.4
  2. Pant     — 675.8
  3. Rohit    — 560.3
  4. Rahul    — 545.2
  5. Iyer     — 534.3
  6. Virat    — 528.0
  7. Gill     — 512.2
  8. Jadeja   — 505.7

Covariance matrix shape: (8, 8)


## Section 7 — Final Challenge: Performance Report
Combining everything into a structured output.

In [21]:
# Pre-compute all metrics
total_runs      = scores.sum(axis=1)
avg_runs        = scores.mean(axis=1)
best_scores     = scores.max(axis=1)
ducks           = (scores == 0).sum(axis=1)
centuries       = (scores > 100).sum(axis=1)
std_scores      = scores.std(axis=1)
consistency     = np.where(std_scores == 0, 0, avg_runs / std_scores)
weights         = np.linspace(0.5, 1.5, 10)
weighted_totals = np.dot(scores, weights)
final_rank      = np.argsort(weighted_totals)[::-1]

print("=" * 52)
print("       TOURNAMENT PERFORMANCE REPORT")
print("=" * 52)

for i in range(len(batsmen)):
    print(f"\n┌{'─'*48}┐")
    print(f"│  Batsman : {batsmen[i]:<36}│")
    print(f"│  Total   : {total_runs[i]:<10}  Average  : {avg_runs[i]:<14.1f}│")
    print(f"│  Best    : {best_scores[i]:<10}  Ducks    : {ducks[i]:<14}│")
    print(f"│  100s    : {centuries[i]:<10}  Consist. : {consistency[i]:<14.2f}│")
    print(f"│  Weighted Total : {weighted_totals[i]:<29.1f}│")
    print(f"└{'─'*48}┘")

print("\n🏆 FINAL RANKING (by weighted score):")
for rank, idx in enumerate(final_rank, 1):
    print(f"  {rank}. {batsmen[idx]:8} — {weighted_totals[idx]:.1f} pts")

       TOURNAMENT PERFORMANCE REPORT

┌────────────────────────────────────────────────┐
│  Batsman : Rohit                               │
│  Total   : 565         Average  : 56.5          │
│  Best    : 134         Ducks    : 1             │
│  100s    : 1           Consist. : 1.47          │
│  Weighted Total : 560.3                        │
└────────────────────────────────────────────────┘

┌────────────────────────────────────────────────┐
│  Batsman : Virat                               │
│  Total   : 538         Average  : 53.8          │
│  Best    : 112         Ducks    : 1             │
│  100s    : 1           Consist. : 1.58          │
│  Weighted Total : 528.0                        │
└────────────────────────────────────────────────┘

┌────────────────────────────────────────────────┐
│  Batsman : Gill                                │
│  Total   : 465         Average  : 46.5          │
│  Best    : 99          Ducks    : 2             │
│  100s    : 0           Consist. 